### ISSUE TITLE
Inquiry on Implementing Trilinear Function on Smartphones

### ISSUE THREAD

**Issue by fenyi2016** [Stephen0808/ICELUT#2]
Very impressive work of an incredibly fast speed of 0.4ms on GPU and 7ms on CPU! 

I have been attempting to implement the trilinear function using TFlite on a low-end smartphone, but I am only able to achieve a runtime of over 500ms for a 480p image. I suspect that the operations I used might be contributing to this slowdown. Specifically, I utilized operations such as stack, gather, cast, and matrix multiplication. Could you please provide some insights or point me towards any resources or code that might help me? 

Thank you very much for your time and assistance.

**Comment by Stephen0808** [comment]
1. Please check the type of CPU. Different types of CPU may result in different latency.
2. Please refer to our codes in trilinear_cpp and follow the installation introduction. 
3. We use AidLux as the platform to test the model in smartphone.

**Comment by fenyi2016** [comment]
Thank you for the information. I ran the code on Aidlux on a low-end smartphone with a Dimensity 720 CPU (Cortex-A76 x2, Cortex-A55 x6). However, I'm only achieving around 50ms for processing a 480p image and 30ms for the trilinear function. Could this be due to not utilizing multiple cores, or is there something else I should be mindful of?

**Comment by Stephen0808** [comment]
Using multiple cores will definitely reduce the latency.
The CPU usage affects the latency. Additionally, different types of smartphone may have various optimization strategy, which is hard for us to reproduce your results.

**Comment by oldtown11** [comment]
> Very impressive work of an incredibly fast speed of 0.4ms on GPU and 7ms on CPU!
> 
> I have been attempting to implement the trilinear function using TFlite on a low-end smartphone, but I am only able to achieve a runtime of over 500ms for a 480p image. I suspect that the operations I used might be contributing to this slowdown. Specifically, I utilized operations such as stack, gather, cast, and matrix multiplication. Could you please provide some insights or point me towards any resources or code that might help me?
> 
> Thank you very much for your time and assistance.

Hello, could you please advise on how to deploy the model to run on a mobile phone? 
Additionally, regarding the conversion of the model to ONNX format, I encountered some difficulties during the process. Would you be able to provide some guidance?

**Comment by Stephen0808** [comment]
According to my experience, I don't think you need the ONNX version of ICELUT. You could  rewrite the inference code in JAVA to build a Andriod package like [SRLUT](https://github.com/yhjo09/SR-LUT). The interpolation codes could be reused.
