### ISSUE TITLE
Is your trilinear function the same in pytorch's implementation?

### ISSUE THREAD

**Issue by minh-nguyenhoang** [Stephen0808/ICELUT#3]
Basically we can reshape the LUT to (1,3,D,H,W) with D=H=W=32 for default setting then using `F.interpolate` with `mode='trilinear'` to map them to (1,3,256,256,256) right? I wonder why all repo use custom trilinear interpolation and not pytorch function?

**Comment by Stephen0808** [comment]
We borrow the existing CUDA operator from [3D LUT](https://github.com/HuiZeng/Image-Adaptive-3DLUT). Seems that this operator is faster than pytorch function.
Anyway, you could try to realize this idea by substituting the CUDA version with F.interpolate.
